### PR TITLE
3-layer declarative plotting

### PR DESCRIPTION
**Pull request by kevindougherty-noaa**
The following scripts can be utilized to plot figures and subplots in a declarative manner. You first create the plot_type object, then the single plot/subplot object, followed by the entire figure. 

IMPORTANT: Colorbar option is still under construction. It works for creating colorbars for multiple subplots, but still needs to be figured out how to best plot a singular colorbar given a colorseries (cs). Will issue new PR once solved.

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]
I think this looks good. It's an impressively short amount of code for quite a bit of stuff.

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA Do you think that `add_<feature>` methods should include documentation of all the input options for the `kwargs`?

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa isn't the normal convention just to have `**kwargs` and nothing else? What does matplotlib, etc. do?

**Comment by kevindougherty-noaa** [comment]
@CoryMartin-NOAA yes, matplotlib only includes `**kwargs`, but also point to where you can see the additional ones. I'm just curious for a users perspective who may not know they can change say 'fontweight' or some other uncommon input. Especially if they are not familiar with python

**Comment by CoryMartin-NOAA** [comment]
@kevindougherty-noaa I think when we write the `eva` documentation, we link to the underlying `matplotlib` documentation for details?

**Pull request merged**
